### ISSUE TITLE
你好，代码运行出现10060错误怎么办

### ISSUE THREAD

**Issue by redwin521** [qiuqingyu/CNKICrawler#2]
代码运行出现10060错误怎么办，另外我想添加共引文献，共引文献数目，参考文献题目，如何修改提取

**Comment by qiuqingyu** [comment]
不好意思哈，这个爬虫我最近一直没有维护，可能需要你自己看下代码添加进去

**Comment by redwin521** [comment]
你好，我配置文件后一直显示FileNotFoundError: [Errno 2] No such file or directory: 'data-detail.txt'
无法运行后添加data-detail.txt，但是无采集数据无更新
